[package]
name = "nexa-ssr"
version = "0.1.0"
edition = "2024"
authors = ["Nexa Team"]
license = "MIT"

[dependencies]
nexa-core = { path = "../nexa-core", version = "0.1.0" }
futures = "0.3"
nexa-scheduler = { path = "../nexa-scheduler", version = "0.1.0" }
