[package]
name = "nexa-router"
version = "0.1.0"
edition = "2024"
authors = ["Nexa Team"]
license = "MIT"

[dependencies]
nexa-core = { path = "../nexa-core", version = "0.1.0" }
nexa-router-macro = { path = "../nexa-router-macro", version = "0.1.0" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = ["History", "Window"] }
wasm-bindgen = "0.2"
