[package]
name = "nexa-rsx"
version = "0.1.0"
edition = "2024"
authors = ["Nexa Team"]
license = "MIT"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
proc-macro2 = "1.0"
[dev-dependencies]
nexa-core = { path = "../nexa-core", version = "0.1.0" }
smallvec = "1.0"
trybuild = "1.0"
